name: Haskell CI
on:
  push:
    #branches:
    #  - master
    tags:
      - 'v*'
  #pull_request:
    #branches:
      #- master
jobs:
  windows:
    runs-on: windows-2019
    outputs:
      filename: ${{ steps.vars.outputs.filename }}
      package_name: ${{ steps.vars.outputs.package_name }}

    steps:
      -
        name: Initialize variables
        id: vars
        # The name from the .cabal file.
        run:
          echo "::set-output name=filename::pandoc-include-code-%GITHUB_REF:*/refs/tags/v=%-pandoc-2.11-windows"
          echo "::set-output name=package_name::pandoc-include-code"

      -
        name: Upload artifact
        run: |
          cd %APPDATA%\local\bin
          cd
          cd "%APPDATA%\local\bin"
          cd
          echo %GITHUB_REF:*/refs/tags/v=%
          echo ${{ needs.windows.outputs.filename }}
          echo ${{ steps.vars.outputs.filename }}
        shell:
          cmd
