name: Haskell CI
on:
  push:
    #branches:
    #  - master
    tags:
      - 'v*'
  #pull_request:
    #branches:
      #- master
jobs:
  windows:
    runs-on: windows-2019
    steps:
      -
        name: Initialize variables
        env:
          # The name from the .cabal file.
          package_name: pandoc-include-code
          package_version: ${GITHUB_REF/refs\/tags\/v}
        id: vars
        run: |
          echo ::set-output name=filename::${{ env.package_name }}-${{ env.package_version }}-pandoc-2.11-windows
          echo ::set-output name=package_name::${{ env.package_name }}

      -
        name: Check out the repository
        uses: actions/checkout@v2

      -
        name: Upload artifact
        run: |
          echo ${{ steps.vars.outputs.package_name }}
          echo '%APPDATA%'
