name: Haskell CI
on:
  push:
    #branches:
    #  - master
    tags:
      - 'v*'
  #pull_request:
    #branches:
      #- master
jobs:
  windows:
    runs-on: windows-2019

    steps:
      -
        name: Initialize variables
        id: vars
        # The name from the .cabal file:
        run:
          echo "::set-output name=bindir::%APPDATA%\local\bin"
          echo "::set-output name=package_name::pandoc-include-code"
          echo "::set-output name=filename::pandoc-include-code-%GITHUB_REF:*refs/tags/v=%-pandoc-2.11-windows"

      -
        name: Upload artifact
        shell:
          cmd
        run: |
          echo "${{ steps.vars.outputs.bindir }}"
          echo "${{ steps.vars.outputs.package_name }}"
          echo "${{ steps.vars.outputs.filename }}"
